dist: bionic
install:
- travis_retry wget https://sdk.dfinity.org/install.sh
- yes Y | sh install.sh
script:
- # Start IC replica.
- dfx start &
- sleep 5
- # Build and install canisters.
- dfx build
- dfx canister install --all
- # Run test suites. 
- dfx canister call format run
- dfx canister call galois run
- dfx canister call version run
