dist: bionic
install:
- travis_retry wget https://sdk.dfinity.org/install.sh
- yes Y | sh install.sh
script:
- dfx start &
- sleep 5
- dfx build
- dfx canister install --all
- dfx canister call test run
- dfx canister call demo encode '(1, variant{M}, variant{Numeric}, "01234567")'
- dfx canister call demo encode '(1, variant{Q}, variant{Alphanumeric}, "HELLO WORLD")'
- dfx canister call demo encode '(2, variant{M}, variant{Alphanumeric}, "HTTPS://SDK.DFINITY.ORG")'
