dist: bionic
install:
- travis_retry wget https://sdk.dfinity.org/install.sh
- yes Y | sh install.sh
script:
- dfx start &
- sleep 5
- dfx build
- dfx canister install --all
- dfx canister call test run
- dfx canister call demo example1 | awk -F '"' -v RS='' '{print ""; print $2}' | sed 's/#/█/g'
